### ISSUE TITLE
Could not pass event PreTransactionEvent to AuxProtect v1.1.5

### ISSUE THREAD

**Issue by smile-minecraft** [Heliosares/AuxProtect#1]
### version
AuxProtect 1.1.5
ESGUI-Premium 3.1.1
### log
```
[04:17:50 ERROR]: Could not pass event PreTransactionEvent to AuxProtect v1.1.5
java.lang.NoSuchMethodError: 'java.lang.String me.gypopo.economyshopgui.api.events.PreTransactionEvent.getTransactionMode()'
        at dev.heliosares.auxprotect.spigot.listeners.EconomyShopGUIListener.onPreTransactionEvent(EconomyShopGUIListener.java:23) ~[AuxProtect-1.1.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor578.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-97]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at me.gypopo.economyshopgui.events.MenuHandler.onMenuClick(MenuHandler.java:131) ~[EconomyShopGUI-Premium-3.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor183.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-97]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3274) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-97]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Heliosares** [comment]
Looks like ESG may have changed their API. Will fix soon.

**Comment by smile-minecraft** [comment]
Thanks!

**Comment by Lariesse** [comment]
> Looks like ESG may have changed their API. Will fix soon.

https://mcpaste.io/e0df5298bcdb159d

Same problem with ShopGUI+ they have updated the api too

**Comment by Heliosares** [comment]
> > Looks like ESG may have changed their API. Will fix soon.
> 
> https://mcpaste.io/e0df5298bcdb159d
> 
> Same problem with ShopGUI+ they have updated the api too

Already fixed in the latest dev build

**Comment by Heliosares** [comment]
Both fixed in latest release. https://github.com/Heliosares/AuxProtect/releases/tag/1.1.6
