### ISSUE TITLE
SQL error when recovering inventories

### ISSUE THREAD

**Issue by Heliosares** [Heliosares/AuxProtect#12]
im gonna add this because i think it still related

what i do is trying to restore a player inventory

```
[Mon 08:36:34 WARN ] AuxProtect Data truncation: Truncated incorrect DOUBLE value: ''
    com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect DOUBLE value: ''
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
    at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.execute(ConnectionPool.java:275)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.lambda$execute$2(ConnectionPool.java:265)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.lambda$execute$1(ConnectionPool.java:191)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.executeReturnException(ConnectionPool.java:242)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.executeReturn(ConnectionPool.java:208)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.execute(ConnectionPool.java:190)
    at AuxProtect.jar//dev.heliosares.auxprotect.database.ConnectionPool.execute(ConnectionPool.java:265)
    at AuxProtect.jar//dev.heliosares.auxprotect.core.commands.InvCommand.update(InvCommand.java:188)
    at AuxProtect.jar//dev.heliosares.auxprotect.core.commands.InvCommand.lambda$makeInventory$2(InvCommand.java:74)
    at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1589)
```

viewing the menu are okay tho
![image](https://user-images.githubusercontent.com/66926348/224589244-9b39aefb-e5ff-42fb-a6a9-ee087ca19860.png)

sorry for the inconvenience, if you need me to test anything im glad to help

_Originally posted by @cupang-afk in https://github.com/Heliosares/AuxProtect/issues/11#issuecomment-1465378245_

**Comment by Heliosares** [comment]
https://github.com/Heliosares/AuxProtect/releases/tag/1.2.5.2-pre3

**Comment by cupang-afk** [comment]
sorry for the late answer

> https://github.com/Heliosares/AuxProtect/releases/tag/1.2.5.2-pre3

after using this update the inventory restoration is fixed (both force recover and regular recover)
