### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by NeadApTar** [Heliosares/AuxProtect#4]
![image](https://user-images.githubusercontent.com/34768994/198995352-b4c9e3bc-b4cf-41de-97ce-c644de23e27b.png)

**Comment by NeadApTar** [comment]
```
[19:09:32 WARN]: [AuxProtect] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTOINCREMENT)' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTOINCREMENT)' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at dev.heliosares.auxprotect.database.SQLManager.execute(SQLManager.java:389) ~[AuxProtect.jar:?]
        at dev.heliosares.auxprotect.database.SQLManager.init(SQLManager.java:302) ~[AuxProtect.jar:?]
        at dev.heliosares.auxprotect.database.SQLManager.connect(SQLManager.java:142) ~[AuxProtect.jar:?]
        at dev.heliosares.auxprotect.spigot.AuxProtectSpigot$1.run(AuxProtectSpigot.java:176) ~[AuxProtect.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-41]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.2.jar:git-Pufferfish-41]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        ```

**Comment by Heliosares** [comment]
https://github.com/Heliosares/AuxProtect/releases/tag/1.2.1-pre1

Please let me know if this works for you.

**Comment by NeadApTar** [comment]
```
[21:18:23 WARN]: [AuxProtect] No value specified for parameter 5
java.sql.SQLException: No value specified for parameter 5
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:379) ~[mysql-connector-java-8.0.29.jar:8.0.29]
        at dev.heliosares.auxprotect.database.InvDiffManager.logInvDiff(InvDiffManager.java:101) ~[AuxProtect.jar:?]
        at dev.heliosares.auxprotect.core.APPlayer.diff(APPlayer.java:138) ~[AuxProtect.jar:?]
        at dev.heliosares.auxprotect.spigot.AuxProtectSpigot$3.run(AuxProtectSpigot.java:341) ~[AuxProtect.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.2.jar:git-Pufferfish-41]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.19.2.jar:git-Pufferfish-41]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by NeadApTar** [comment]
Everything seems to be fine now
